services:
  api:
    build: ./
    ports:
      - '8080:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/ideanest-task
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
